ROWS = 12
COLS = 16
TILE_SIZE = 64
SIDE_PANEL = 256
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 1
MONEY = 650
TOTAL_LEVELS = 3

#enemy constants
SPAWN_COOLDOWN = 1000
KILL_REWARD = 50

LEVEL_COMPLETE_REWARD = 100

ANIMATION_STEPS = 8
ANIMATION_DELAY = 50